9jaTips.Web/Controllers/MiscController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _9jaTips.Services.Interfaces;
using _9jaTips.Services.Repositories;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace _9jaTips.Web.Controllers
{
    public class MiscController : Controller
    {
        private readonly IFixtures _fixtures;

        public MiscController(IFixtures fixtures)
        {
            _fixtures = fixtures;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult TrendingLeagues()
        {
            return View();
        }

        public IActionResult Table()
        {
            return View();
        }
    }
}

9jaTips.Web/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using _9jaTips.Entities;
using _9jaTips.Services.Interfaces;
using _9jaTips.Web.ViewModels;
using Humanizer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace _9jaTips.Web.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private readonly IFixtures _fixtures;
        private readonly UserManager<AppUser> userManager;
        private readonly SignInManager<AppUser> signInManager;

        public PostController(IFixtures fixtures, UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            _fixtures = fixtures;
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            var posts = _fixtures.GetAllPosts();

            var modelList = new List<ListPostViewModel>();

            foreach(var post in posts)
            {
                var model = new ListPostViewModel
                {
                    Fixture = _fixtures.GetMatchById(post.MatchId),
                    Id = post.Id,
                    Thoughts = post.Thoughts,
                    Tip = post.Tip,
                    UserId = post.AppUserId
                };
                modelList.Add(model);
            }
            return View(modelList);
        }

        [HttpGet]
        public async Task<IActionResult> FilterPost(string country)
        {
            var posts = _fixtures.GetCountryPosts(country);

            ViewBag.Country = country;

            var modelList = new List<ListPostViewModel>();

            foreach (var post in posts)
            {
                var user = await userManager.FindByIdAsync(post.AppUserId.ToString());
                var streak = _fixtures.GetUserStreak(post.AppUserId);
                var model = new ListPostViewModel
                {
                    Fixture = _fixtures.GetMatchById(post.MatchId),
                    Id = post.Id,
                    Thoughts = post.Thoughts,
                    Tip = post.Tip,
                    UserId = post.AppUserId,
                    PostDate = post.PostDate.Humanize(),
                    Comments = post.Comments,
                    Image = user.Image,
                    Streak = streak
                };
                modelList.Add(model);
            }
            return View(modelList.Reverse<ListPostViewModel>().ToList());
        }

        public IActionResult Countries()
        {
            ViewBag.Countries = _fixtures.GetCountries();
            return View();
        }

        public IActionResult Leagues(string country)
        {
            ViewBag.Leagues = _fixtures.GetLeagues(country);

            ViewBag.Country = country;
            return View();
        }

        public IActionResult Fixtures(string country, string league)
        {
            var matches = _fixtures.GetFixtures(country, league);

            return View(matches);
        }

        public IActionResult Picks(int matchId)
        {
            var match = _fixtures.GetMatchById(matchId);

            return View(match);
        }

        [HttpGet]
        public IActionResult Predict(int matchId, string selection)
        {

            PostViewModel model = new PostViewModel
            {
                AppUserId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)),
                MatchId = matchId,
                Tip = selection,
                Fixture = _fixtures.GetMatchById(matchId)
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            if (!signInManager.IsSignedIn(User))
            {
                return RedirectToAction("Index");
            }

            var post = _fixtures.GetPostById(id);
            var match = _fixtures.GetMatchById(post.MatchId);
            var user = await userManager.FindByIdAsync(post.AppUserId.ToString());

            var postComments = new List<CommentsViewModel>();

            foreach(var comment in post.Comments)
            {
                var streak = _fixtures.GetUserStreak(comment.AppUserId);
                var pc = new CommentsViewModel
                {
                    AppUserId = comment.AppUserId,
                    Id = comment.Id,
                    Message = comment.Message,
                    PostId = comment.PostId,
                    Time = comment.TimeStamp.Humanize(),
                    Streak = streak
                };
                postComments.Add(pc);
            }

            if (post != null)
            {
                DetailsViewModel model = new DetailsViewModel
                {
                    AppUserId = post.AppUserId,
                    PostComments = postComments.Reverse<CommentsViewModel>().ToList(),
                    Id = post.Id,
                    TimeStamp = post.PostDate.Humanize(),
                    Thoughts = post.Thoughts,
                    Prediction = $"{match.Home} vs {match.Away} #{post.Tip}",
                    Location = $"{match.League} in {match.Country}",
                    UserImage = user.Image
                };

                return View(model);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Details(DetailsViewModel model)
        {
            // Check if postID exist
            if (model.Id != null)
            {
                Comment comment = new Comment
                {
                    AppUserId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)),
                    Message = model.Message,
                    PostId = model.Id,
                    TimeStamp = DateTime.Now
                };

                var saved = _fixtures.AddComment(comment);

                if (saved != null)
                {
                    return RedirectToAction("Details", new { id = model.Id });
                }

                return View(model);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Predict(PostViewModel model)
        {
            if (ModelState.IsValid)
            {
                Post post = new Post
                {
                    AppUserId = model.AppUserId,
                    Tip = model.Tip,
                    Thoughts = model.Thoughts,
                    MatchId = model.MatchId,
                    PostDate = DateTime.Now,
                    Outcome = "Pending"
                };

                _fixtures.AddPost(post);
                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }

        //[HttpPost]
        //public IActionResult Like(Guid postId)
        //{
        //    var check = _fixtures.HasLiked(postId, Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)));
        //    if (check == false)
        //    {
        //        Like like = new Like
        //        {
        //            PostId = postId,
        //            UserId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier))
        //        };
        //        _fixtures.AddLike(like);
        //        string referer = Request.Headers["Referer"].ToString();
        //        return Redirect(referer);
        //    }
        //    string referrer = Request.Headers["Referer"].ToString();
        //    return Redirect(referrer);
        //}

        [HttpPost]
        public IActionResult Like(Like model)
        {
            if (model != null)
            {
                var check = _fixtures.HasLiked(model.PostId, Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)));
                if (check == null)
                {
                    Like like = new Like
                    {
                        PostId = model.PostId,
                        UserId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier))
                    };
                    var result = _fixtures.AddLike(like);
                    if (result != null)
                    {
                        return Json(new { data = result, added = true });
                    }
                }
                else
                {
                    var unliked = _fixtures.Unlike(model.PostId, Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)));
                    if (unliked != null)
                    {
                        return Json(new { data = unliked, removed = true });
                    }
                }
            }

            return Json(new { message = "An Error Occurred" });

        }

        [HttpPost]
        public IActionResult DeletePost(Guid id)
        {
            var deletedPost = new Post();
            if (id != null)
            {
                deletedPost = _fixtures.DeletePost(id);
            }
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return RedirectToAction("Index", "Profile", new { Id = userId });
        }

        // AJAX
        public async Task<IActionResult> GetOne(Guid id)
        {
            var post = _fixtures.GetOnePost(id);
            var user = await userManager.FindByIdAsync(post.AppUserId.ToString());
            if (post != null)
            {
                var postInfo = new AjaxPostViewModel
                {
                    Id = post.Id,
                    Location = $"{_fixtures.GetMatchById(post.MatchId).League} in {_fixtures.GetMatchById(post.MatchId).Country}",
                    Thoughts = post.Thoughts,

9jaTips.Web/Views/Shared/_Layout.cshtml
@inject SignInManager<AppUser> signInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _9jaTips.Web</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    @*<div style="height:100%;" id="topper">*@
    <header id="header">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-danger" asp-area="" asp-controller="Home" asp-action="Index">_9jaTips.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link hidden-link" asp-area="" asp-controller="Misc" asp-action="TrendingLeagues">Leagues</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link hidden-link" asp-area="" asp-controller="Misc" asp-action="Table">Table</a>
                        </li>

                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <form class="nav-link py-0" asp-area="" asp-controller="Account" asp-action="Logout">
                                    <button type="submit" class="nav-link border-0 text-center text-light pt-1 logout pt-2" style="width: 100%;background:none;font-weight:bold">Logout</button>
                                </form>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Post" asp-action="Countries">Post</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Profile" asp-action="Index" asp-route-id="@User.FindFirstValue(ClaimTypes.NameIdentifier)"><i class="fa fa-user"></i> @User.FindFirstValue(ClaimTypes.Name).Split('@')[0]</a>

                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }



                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid" id="fluid">
        <main role="main" class="pb-3">

            <div class="row">
                <div class="col-lg-3" id="leagues">
                    <div class="card border-0">
                        <div class="card-header h5">
                            Leagues
                        </div>
                        <div class="card-body border-0">
                            <ul class="list-group font-weight-bold" id="list">
                                <li class="list-group-item"><a asp-controller="Post" asp-action="FilterPost" asp-route-country="England">EPL</a></li>
                                <li class="list-group-item"><a asp-controller="Post" asp-action="FilterPost" asp-route-country="Spain">La Liga</a></li>
                                <li class="list-group-item"><a asp-controller="Post" asp-action="FilterPost" asp-route-country="Germany">Bundesliga</a></li>
                                <li class="list-group-item"><a asp-controller="Post" asp-action="FilterPost" asp-route-country="Netherland">Eredivisie</a></li>
                                <li class="list-group-item"><a asp-controller="Post" asp-action="FilterPost" asp-route-country="Italy">Serie A</a></li>
                                <li class="list-group-item"><a asp-controller="Post" asp-action="FilterPost" asp-route-country="France">Ligue 1</a></li>
                                <li class="list-group-item"><a asp-controller="Post" asp-action="FilterPost" asp-route-country="Nigeria">NPFL</a></li>
                                <li class="list-group-item"><a asp-controller="Post" asp-action="FilterPost" asp-route-country="South Africa">ABSA</a></li>
                                <li class="list-group-item"><a asp-controller="Post" asp-action="FilterPost" asp-route-country="Belgium">Super League</a></li>
                                <li class="list-group-item"><a asp-controller="Post" asp-action="FilterPost" asp-route-country="International">Champions League</a></li>
                                <li class="list-group-item"><a asp-controller="Post" asp-action="FilterPost" asp-route-country="Belgium">Pro League</a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="col-md-12 col-lg-6" id="main">
                    @RenderBody()
                </div>

                <div class="col-lg-3" id="standings">
                    <div class="card border-0">
                        <div class="card-header h5">
                            Standings
                        </div>
                        <div class="card-body">
                            <table class="table table-striped table-hover" style="width:100%">
                                <tr>
                                    <th>S/N</th>
                                    <th>Name</th>
                                    <th>P</th>
                                </tr>
                                <tbody>
                                    <tr>
                                        <td>1.</td>
                                        <td>Username</td>
                                        <td>9</td>
                                    </tr>
                                    <tr>
                                        <td>2.</td>
                                        <td>Username</td>
                                        <td>9</td>
                                    </tr>
                                    <tr>
                                        <td>3.</td>
                                        <td>Username</td>
                                        <td>9</td>
                                    </tr>
                                    <tr>
                                        <td>4.</td>
                                        <td>Username</td>
                                        <td>9</td>
                                    </tr>
                                    <tr>
                                        <td>5.</td>
                                        <td>Username</td>
                                        <td>9</td>
                                    </tr>
                                    <tr>
                                        <td>6.</td>
                                        <td>Username</td>
                                        <td>9</td>
                                    </tr>
                                    <tr>
                                        <td>7.</td>
                                        <td>Username</td>
                                        <td>9</td>
                                    </tr>
                                    <tr>
                                        <td>8.</td>
                                        <td>Username</td>
                                        <td>9</td>
                                    </tr>
                                    <tr>
                                        <td>9.</td>
                                        <td>Username</td>
                                        <td>9</td>
                                    </tr>
                                    <tr>
                                        <td>10.</td>
                                        <td>Username</td>
                                        <td>9</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>


            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - _9jaTips.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    @*</div>*@
</body>
</html>